use_frameworks!

platform :ios, '9.0'

target 'GalleryDemo' do
 pod 'Gallery', :git => 'https://github.com/loloa/Gallery.git', :branch => 'master'
 pod 'Lightbox'
 pod 'Hue'
 pod 'SVProgressHUD'
end

